# Site settings
title: Wanderer's musings
email: null_radix@riseup.net
username: wanderer
description: "Wanderer aka null_radix writes things here. Mainly about programming"

# Build settings
markdown: kramdown
permalink: pretty
